# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0b3281965a63800321ce693c31e07493a8f2895d9f897c1dbef96123ad6d043b00e5a4391d40c572942b7db9e2e434dea5cb16045106eaf93b2dec3a4287748

test:
  secret_key_base: a7004c995f6a9f6ca2d51fa3c648e71d7a5c3b12aeb35ee58b6780ef6a669af2098cd16395cbd18bb561a13a60c597b56082025f400954741efedc6df032d509

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
